# Generated by Django 5.2.9 on 2025-12-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='Ссылка на YouTube трейлер', null=True),
        ),
    ]
