# Generated by Django 6.0 on 2025-12-25 08:15

import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movieview_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=movies.models.poster_upload_path),
        ),
    ]
